export enum Departmanlar{
  FRONTEND_GELISTIRME = 0,
  BACKEND_GELISTIRME = 1,
  MOBIL_GELISTIRME = 2,
  DEVOPS = 3,
  SISTEM_DESTEK = 4,
  URUN_GELISTIRME = 5,
  INSAN_KAYNAKLARI = 6,
  EGITIM_TEKNOLOJILERI = 7,
  PAZARLAMA = 8,
  DIGER = 9,


}
